language: node_js
node_js:
  - "6.11.1"

before_script:
  - npm install -g gulp
  - rvm install ruby
  - gem install scss_lint

script:
  - gulp all

cache:
  directories:
  - bower_components
  - node_modules

