version: '3'
services:
 visflow:
  build: 
   context: .
   dockerfile: Dockerfile
  ports: 
   - '80:80'
   - '443:443'
  volumes:
   - visflow_volume:/data/visflow
 database:
  build: 
   context: .
   dockerfile: Dockerfile.db
  ports: 
   - '3306:3306'
  environment:
   MYSQL_ROOT_PASSWORD: 'root'
  volumes:
   - database_volume:/var/lib/mysql 
volumes:
 database_volume:
 visflow_volume: