#!/bin/sh

sed -i "s:^\(d3m_config *= *\).*:\1$1:" server/config
echo $$ > /data/visflow.pid
if [ ! -f "/servers_started.flag" ]; then
  touch /servers_started.flag
  start-script.sh
fi
while true; do
  sleep 1
done
