# Base image: Apache, PHP on Debian:jessie
FROM mysql/mysql-server:5.7

LABEL maintainer="{jorgehpo, remi.rampin, yamuna, raonipd, bowen.yu}@nyu.edu"

WORKDIR /docker-entrypoint-initdb.d/

ADD server/init.sh /docker-entrypoint-initdb.d/
ADD server/init-db.sql /docker-entrypoint-initdb.d/
ADD server/config /docker-entrypoint-initdb.d/

ENV MYSQL_ROOT_PASSWORD root

EXPOSE 3306